name: Build, Test, Document, Dialyze

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Erlang/OTP ${{matrix.otp}} / rebar3 ${{matrix.rebar3}}
    strategy:
      matrix:
        otp: ['24.3.4', '25.2.1']
        rebar3: ['3.20.0']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{matrix.rebar3}}
      - name: Run tests
        run: rebar3 ct
      - name: ExDoc Documentation
        run: if [ $(rebar3 version | awk '{print $5}') -gt 23 ]; then rebar3 ex_doc; fi;
      - shell: bash
        name: Dialyzer
        run: rebar3 dialyzer

# Windows CI disabled: nmake is missing from setup-beam@v1
#  windows:
#    name: Test on Windows
#    runs-on: windows-2022
#    steps:
#      - uses: actions/checkout@v3
#      - uses: erlef/setup-beam@v1
#        with:
#          otp-version: '24'
#          rebar3-version: '3.16.1'
#      - run: rebar3 ct

  macos:
    name: Test on MacOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Erlang
        run: brew install erlang rebar3
      - name: Run tests
        run: rebar3 ct